name: Cleanup PR preview

on:
  pull_request:
    types: [ closed ]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Remove preview directory
        run: |
          dir="previews/pr-${{ github.event.number }}"
          if [ -d "$dir" ]; then
            git rm -r "$dir"
            git commit -m "Remove preview for PR #${{ github.event.number }}"
            git push origin HEAD:gh-pages
          else
            echo "No preview directory for PR #${{ github.event.number }}"
          fi
