name: Preview GitHub Pages Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to preview"
        required: true
        default: main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-preview-${{ github.event.inputs.ref && replace(github.event.inputs.ref, '/', '-') || 'main' }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy preview to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          preview: true
